### ISSUE TITLE
Unable to update dataset metadata (DOI: 10.5061/dryad.m874vg5)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3519]
Can you help me make the following edits to this dataset? I keep receiving the error message below. 
**10.5061/dryad.m874vg5**

1) Add article DOI: https://doi.org/10.1111/mec.15280
2) Add submitting author's email: maria.rebolleda-gomez@yale.edu
3) Remove 3rd author (same as submitting author)

![Screenshot 2024-07-16 at 5 17 31 PM](https://github.com/user-attachments/assets/2ea58911-5fc9-448f-9b0a-6bb761b0933d)

**Comment by ahamelers** [comment]
@jleighherzog Can you try updating the DOI again? There was a bug around that (when the same DOI already appears in the related works list) that was fixed in the most recent release. If that was the problem that should be fixed now

**Comment by jleighherzog** [comment]
@ahamelers : I still receive errors

- Fill 3rd author's [institutional affiliation](https://datadryad.org/stash/metadata_entry_pages/find_or_create?display_validation=true&resource_id=305979#instit_affil__1406931)
- Fill in [submitting author's email](https://datadryad.org/stash/metadata_entry_pages/find_or_create?display_validation=true&resource_id=305979#author_email__)

**Comment by ahamelers** [comment]
@jleighherzog I wonder if the submitting author is not actually the first in the author order, but the 3rd! I'll check the database

**Comment by ahamelers** [comment]
@jleighherzog I think my instinct was right—a new submitting author is being generated as the 3rd author, because neither of the existing authors is connected to any account with an ORCID. I'll see if I can find the correct ORCID for the submitter and add it!

**Comment by ahamelers** [comment]
Okay, I added the ORCID to the user and the author, and the email to the author. All should work now @jleighherzog !
